limubacadministrator_homepage:
    path:     /admin
    defaults: { _controller: limubacadministratorBundle:Default:admin}

limubacadministrator_hojaAnotaciones:
    path:     /hojaAnotaciones/{idpartido}
    defaults: { _controller: limubacadministratorBundle:HojaAnotaciones:hojaAnotaciones,idpartido:0}

limubacadministrator_nombresEquipos:
    path:     /nombresEquipos
    defaults: { _controller: limubacadministratorBundle:HojaAnotaciones:nombresEquipos}

limubacadministrator_equipos:
    path:     /equipos
    defaults: { _controller: limubacadministratorBundle:Equipos:equipos}

limubacadministrator_equipo:
    path:     /equipo
    defaults: { _controller: limubacadministratorBundle:Equipos:equipo}

limubacadministrator_jugadoresAdmin:
    path:     /jugadoresAdmin
    defaults: { _controller: limubacadministratorBundle:Default:jugadoresAdmin}

limubacadministrator_addjugador:
    path:     /addjugador
    defaults: { _controller: limubacadministratorBundle:Default:addjugador}

limubacadministrator_upload:
    path:     /upload
    defaults: { _controller: limubacadministratorBundle:Upload:upload}

limubacadministrator_uploados:
    path:     /uploados
    defaults: { _controller: limubacadministratorBundle:Default:uploados}

limubacadministrator_update:
    path:     /update/{page}
    defaults: { _controller: limubacadministratorBundle:Default:update, page: 0}

limubacadministrator_buscar:
    path:     /buscar/{page}
    defaults: { _controller: limubacadministratorBundle:Default:buscar, page: 0}

limubacadministrator_editar:
    path:     /editar
    defaults: { _controller: limubacadministratorBundle:Default:editar}

limubacadministrator_photo:
    path:     /photo/{number}
    defaults: { _controller: limubacadministratorBundle:Default:photo}
    requirements:
        number: \d+

limubacadministrator_torneos:
    path:     /torneos
    defaults: { _controller: limubacadministratorBundle:Default:torneos}

limubacadministrator_crearTorneo:
    path:     /crearTorneo
    defaults: { _controller: limubacadministratorBundle:Default:crearTorneo}

limubacadministrator_categorias:
    path:     /categorias
    defaults: { _controller: limubacadministratorBundle:Default:categorias}

limubacadministrator_crearCategoria:
    path:     /crearCategoria
    defaults: { _controller: limubacadministratorBundle:Default:crearCategoria}

limubacadministrator_acTorneo:
    path:     /acTorneo
    defaults: { _controller: limubacadministratorBundle:Default:acTorneo}

limubacadministrator_editTorneo:
    path:     /editTorneo
    defaults: { _controller: limubacadministratorBundle:Default:editTorneo}

limubacadministrator_acCategoria:
    path:     /acCategoria
    defaults: { _controller: limubacadministratorBundle:Default:acCategoria}
    
limubacadministrator_editCategoria:
    path:     /editCategoria
    defaults: { _controller: limubacadministratorBundle:Default:editCategoria}

limubacadministrator_rol:
    path:     /rol
    defaults: { _controller: limubacadministratorBundle:Default:rol}

limubacadministrator_partidos:
    path:     /partidos
    defaults: { _controller: limubacadministratorBundle:Partidos:partidoTest}

limubacadministrator_addrol:
    path:     /addrol
    defaults: { _controller: limubacadministratorBundle:Default:addrol}
