limubacadministrator_homepage:
    path:     /admin
    defaults: { _controller: limubacadministratorBundle:Default:admin}

limubacadministrator_hojaAnotaciones:
    path:     /hojaAnotaciones
    defaults: { _controller: limubacadministratorBundle:Default:hojaAnotaciones}

limubacadministrator_equipos:
    path:     /equipos
    defaults: { _controller: limubacadministratorBundle:Default:equipos}

limubacadministrator_equipo:
    path:     /equipo
    defaults: { _controller: limubacadministratorBundle:Default:equipo}