
limubac\administratorBundle\claseForm\Author:
    properties:
        name:
            - Email: ~

limubac\administratorBundle\claseForm\hojaAnotacion:
    properties:
        EqA:
            - NotBlank: ~