<?php

namespace limubac\administratorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * faltas_equipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class faltas_equipoRepository extends EntityRepository
{
}
