<?php

namespace limubac\administratorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * arbitroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class arbitroRepository extends EntityRepository
{
}
