<?php

namespace limubac\administratorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * participan_TRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participan_TRepository extends EntityRepository
{
}
