<?php

namespace limubac\administratorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * rama_equipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rama_equipoRepository extends EntityRepository
{
}
